version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - securetalk_mongo-data:/data/db
    networks:
      - securetalk_network

  backend:
    build: ./server
    container_name: backend
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/securetalk
    depends_on:
      - mongodb
    networks:
      - securetalk_network

  frontend:
    build: ./client
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - securetalk_network

volumes:
  securetalk_mongo-data:
    driver: local

networks:
  securetalk_network:
    driver: bridge
